scan_timeout = 60
add_newline = false

format = """\
($directory)\
$os\
$git_branch\
$git_status\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$status\
$cmd_duration\
$time\
\n$character
"""

[fill]
symbol = ' '

# ConfiguraciÃ³n del sÃ­mbolo del prompt
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[line_break]
disabled = false

[directory]
style = "bold blue"
home_symbol = "ï€• "
truncate_to_repo = true

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "ï€"
not_executable_symbol = "ï‘®"
sigint_symbol = "ï­¦"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ï˜ "                           # Branch with oriental touch

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[package]
format = "[$symbol$version]($style) "
symbol = "î¬© "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "î˜† "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = "î˜ˆ "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = "î‰– "

[rust]
format = "[$symbol($version )]($style)"
symbol = "ğŸ¦€ "

[golang]
format = "[$symbol($version )]($style)"
symbol = "î˜¦ "

[lua]
format = "[$symbol($version )]($style)"
symbol = "î˜  "

[c]
format = "[$symbol($version )]($style)"
symbol = "î˜ "

[battery]
disabled = true

[localip]
disabled = false
ssh_only = false
format = '[$localipv4]($style) '
style = 'bold cyan'

[username]
disabled = false
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style) '
show_always = true

[sudo]
disabled = false
style = 'bold yellow'
format = '[$symbol]($style)'
symbol = 'ó°ˆ¸ '
